DISTRO = "sandbox"
DISTRO_CODENAME = "scarthgap"
DISTRO_VERSION = "1.0"

# DISTRO_FEATURES = "acl ipv4 ipv6 usbhost wifi xattr nfs zeroconf vfat seccomp"
DISTRO_FEATURES:remove = "alsa bluetooth debuginfod pcmcia usbgadget pci 3g nfc x11 pulseaudio"

INIT_MANAGER = "${INITM}"

BUILD_TYPE ?= "release"
EXTRA_IMAGE_FEATURES:append = "${@bb.utils.contains('BUILD_TYPE', 'dev', ' tools-debug debug-tweaks dbg-pkgs', '', d)}"
DEBUG_BUILD = "${@bb.utils.contains('BUILD_TYPE', 'dev', 1, 0, d)}"
INHIBIT_PACKAGE_DEBUG_SPLIT = "${DEBUG_BUILD}"

PACKAGE_EXCLUDE = "${PKG_EXCLUDE}"
NO_RECOMMENDATIONS = "1"

# Enable CVE checking
INHERIT += "cve-check"

# Disable GPLv3 packages (Commented until a custom image is created)
# INCOMPATIBLE_LICENSE = "GPL-3.0* LGPL-3.0*"

# Generate license manifest
INHERIT += "license"
COPY_LIC_MANIFEST = "1"

# Enable build history 
INHERIT += "buildhistory image-buildinfo"
BUILDHISTORY_DIR = "/work/build/build-history"
BUILDHISTORY_FEATURES = "image"