# meta-sandbox-bsp/conf/machine/sandbox-stm32mp25.conf

require conf/machine/stm32mp25-disco.conf

MACHINEOVERRIDES =. "sandbox:"

DEFAULTTUNE = "cortexa35"

BOOTSCHEME_LABELS = "optee"

BOOTDEVICE_LABELS = "sdcard"
