# meta-sandbox-bsp/conf/machine/sandbox-stm32mp15.conf

require conf/machine/stm32mp15-disco.conf

MACHINEOVERRIDES =. "sandbox-stm32mp15:"

DEFAULTTUNE = "cortexa7thf-neon-vfpv4"

BOOTSCHEME_LABELS = "optee"

BOOTDEVICE_LABELS = "sdcard"
